### PR TITLE
Added option to sort URLs alphabetically.

### PR DESCRIPTION
**Pull request by paleite**

### CODE REVIEW

**Comment by balupton** [comment]
Hey! Why is this useful? Knowing that will let me know the context for the review.

**Comment by paleite** [comment]
Hey!
At our company, we always diff the generated files to see exactly what has changed. We do this for security reasons.
The sitemap always changes the order of its entries, making it hard to diff.
Sorting the entries makes it trivial ?

On 26 sep. 2015, at 02:36, Benjamin Lupton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey! Why is this useful? Knowing that will let me know the context for the review.

-

**Comment by balupton** [comment]
happy to merge this, but PR is now outdated - sorry about that, can you re-apply

also, happy to make that sorting technique the default, as it makes sense

also, what is this change about? `lastmodISO: document.get('mtime').toISOString().slice 0, 10`

**Comment by balupton** [comment]
I have become too preoccupied by other things to review, merge, and release this PR.

However, you should have received an invite a while ago to join the DocPad Extras Team, which will give you write access to this repository, so you can merge in the PR, and become one of the maintainers of this repository.

For an orientation, or if you need any assistance following the semi-automatic release process from `CONTRIBUTING.md`, reach out via https://bevry.me/discord/dev

**Pull request closed without merging**
